### ISSUE TITLE
Hardcoded pingdom ips

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/make-recall-decision-ui#1327]
Hi we noticed hardcoded pingdom ips in a whitelist.

https://github.com/ministryofjustice/make-recall-decision-ui/blob/2e2d3448e68b3ae5a006165f7e1009a9b34e085b/helm_deploy/values-prod.yaml#L23

We were thinking of implementing something similar in our team but were recommended to use the [health-kick](https://github.com/ministryofjustice/health-kick) proxy

Slack thread here:

https://mojdt.slack.com/archives/C06MWP0UKDE/p1729676703293929

Maybe you'd find this helpful 🤞🏾

**Comment by MancRickster** [comment]
Hey Abdi (@Obsiye), nice one, thanks , I'll take a look
R
